if vim.g.colors_name then
	vim.cmd("hi clear")
end

vim.g.colors_name = "ice"

local c = {
	white = '#FFFFFF',
	black = '#000000',

	lsp_inlay_hint = '#969696',

	accent = '#59C2FF',
	bg = '#000000',
	fg = '#dddddd',

	tag = '#dddddd',
	func = '#65d1ff', -- functions
	entity = '#59C2FF', -- Types
	string = '#c6efff',
	regexp = '#95E6CB',
	markup = '#d1e3ff',
	keyword = '#eeffff',
	special = '#ffffff',
	comment = '#636A72',
	constant = '#0475a4',
	operator = '#eeffff',
	lsp_parameter = '#dddddd',

	line = '#222222',
	panel_bg = '#0F131A',
	panel_shadow = '#05070A',
	panel_border = '#000000',
	gutter_normal = '#454B55',
	gutter_active = '#626975',
	selection_inactive = '#122132',
	selection_border = '#304357',
	guide_active = '#3C414A',
	guide_normal = '#1E222A',

	vcs_added = '#7FD962',
	vcs_modified = '#73B8FF',
	vcs_removed = '#F26D78',

	error = '#D95757',
	warning = '#FF8F40',

	vcs_added_bg = '#1D2214',
	vcs_removed_bg = '#2D2220',

	fg_idle = '#565B66',
}

local groups = {
	-- Base.
	Normal = { fg = c.fg, bg = c.bg },
	NormalFloat = { bg = c.bg },
	FloatBorder = { fg = c.comment },
	FloatTitle = { fg = c.fg },
	ColorColumn = { bg = c.line },
	Cursor = { fg = c.bg, bg = c.fg },
	CursorColumn = { bg = c.line },
	CursorLine = { bg = c.line },
	CursorLineNr = { fg = c.keyword, bg = c.line, bold = true },
	LineNr = { fg = c.guide_normal },

	Directory = { fg = c.func },
	ErrorMsg = { fg = c.error },
	WinSeparator = { fg = c.panel_border, bg = c.bg },
	VertSplit = { link = 'WinSeparator' },
	Folded = { fg = c.fg_idle, bg = c.panel_bg },
	FoldColumn = { bg = c.bg },
	SignColumn = { bg = c.bg },

	MatchParen = { sp = c.func, underline = true },
	ModeMsg = { fg = c.string },
	MoreMsg = { fg = c.string },
	NonText = { fg = c.guide_normal },
	Pmenu = { fg = c.fg, bg = c.selection_inactive },
	PmenuSel = { fg = c.fg, bg = c.selection_inactive, reverse = true },
	Question = { fg = c.string },
	Search = { fg = c.bg, bg = c.constant },
	CurSearch = { fg = c.bg, bg = c.special },
	IncSearch = { fg = c.keyword, bg = c.selection_inactive },
	SpecialKey = { fg = c.selection_inactive },
	SpellCap = { sp = c.tag, undercurl = true },
	SpellLocal = { sp = c.keyword, undercurl = true },
	SpellBad = { sp = c.error, undercurl = true },
	SpellRare = { sp = c.regexp, undercurl = true },
	StatusLine = { fg = c.fg, bg = c.panel_bg },
	StatusLineNC = { fg = c.fg_idle, bg = c.panel_bg },
	WildMenu = { fg = c.fg, bg = c.markup },
	TabLine = { fg = c.comment, bg = c.panel_shadow },
	TabLineFill = { fg = c.fg, bg = c.panel_border },
	TabLineSel = { fg = c.fg, bg = c.bg },
	Title = { fg = c.keyword },
	Visual = { bg = c.selection_inactive },
	WarningMsg = { fg = c.warning },

	Comment = { fg = c.comment, italic = true },
	Constant = { fg = c.constant },
	String = { fg = c.string },
	Identifier = { fg = c.entity },
	Function = { fg = c.func },
	Statement = { fg = c.keyword, bold = true },
	Operator = { fg = c.operator },
	Exception = { fg = c.markup },
	PreProc = { fg = c.accent },
	Type = { fg = c.entity },
	Structure = { fg = c.special },
	Special = { fg = c.accent },
	Delimiter = { fg = c.special },
	Underlined = { sp = c.tag, underline = true },
	Ignore = { fg = c.fg },
	Error = { fg = c.white, bg = c.error },
	Todo = { fg = c.markup },
	qfLineNr = { fg = c.keyword },
	qfError = { fg = c.error },
	Conceal = { fg = c.comment },
	CursorLineConceal = { fg = c.guide_normal, bg = c.line },

	Added = { fg = c.vcs_added },
	Removed = { fg = c.vcs_removed },
	Changed = { fg = c.vcs_modified },
	DiffAdd = { bg = c.vcs_added_bg },
	DiffAdded = { fg = c.vcs_added },
	DiffDelete = { bg = c.vcs_removed_bg },
	DiffRemoved = { fg = c.vcs_removed },
	DiffText = { bg = c.gutter_normal },
	DiffChange = { bg = c.selection_inactive },

	-- LSP.
	DiagnosticError = { fg = c.error },
	DiagnosticWarn = { fg = c.keyword },
	DiagnosticInfo = { fg = c.tag },
	DiagnosticHint = { fg = c.regexp },

	DiagnosticUnderlineError = { sp = c.error, undercurl = true },
	DiagnosticUnderlineWarn = { sp = c.keyword, undercurl = true },
	DiagnosticUnderlineInfo = { sp = c.tag, undercurl = true },
	DiagnosticUnderlineHint = { sp = c.regexp, undercurl = true },

	-- Markdown.
	markdownCode = { fg = c.special },

	-- TreeSitter.
	['@property'] = { fg = c.tag },
	['@tag'] = { fg = c.keyword },
	['@tag.attribute'] = { fg = c.entity },
	['@tag.delimiter'] = { link = 'Delimiter' },
	['@type.qualifier'] = { fg = c.keyword },
	['@variable'] = { fg = c.fg },
	['@variable.builtin'] = { fg = c.func },
	['@variable.member'] = { fg = c.tag },
	['@variable.parameter'] = { fg = c.fg },
	['@module'] = { fg = c.entity },
	['@markup.heading'] = { fg = c.keyword },
	['@keyword.storage'] = { fg = c.keyword },
	['@function.builtin'] = { link = "Statement" },

	['@lsp.type.namespace'] = { link = '@module' },
	['@lsp.type.type'] = { link = '@type' },
	['@lsp.type.class'] = { link = '@type' },
	['@lsp.type.enum'] = { link = '@type' },
	['@lsp.type.interface'] = { link = '@type' },
	['@lsp.type.struct'] = { link = '@type' },
	['@lsp.type.parameter'] = { fg = c.lsp_parameter },
	['@lsp.type.field'] = { link = '@variable.member' },
	['@lsp.type.variable'] = { link = '@variable' },
	['@lsp.type.property'] = { link = '@property' },
	['@lsp.type.enumMember'] = { link = '@constant' },
	['@lsp.type.function'] = { link = '@function' },
	['@lsp.typemod.function.constant'] = { link = '@function' },
	['@lsp.typemod.method.constant'] = { link = '@function' },
	['@lsp.type.method'] = { link = '@function.method' },
	['@lsp.type.macro'] = { link = '@function.macro' },
	['@lsp.type.decorator'] = { link = '@function' },
	['@lsp.mod.constant'] = { link = '@constant' },

	-- TreesitterContext.
	TreesitterContext = { bg = c.selection_inactive },

	-- Blink Cmp
	BlinkCmpMenu = { bg = c.bg },
	BlinkCmpMenuBorder = { bg = c.bg },
	BlinkCmpMenuSelection = { bg = c.selection_inactive },
	BlinkCmpScrollBarGutter = { bg = c.line },
	BlinkCmpScrollBarThumb = { bg = c.fg_idle },
	BlinkCmpLabel = { fg = c.fg_idle },
	BlinkCmpLabelDeprecated = { fg = c.comment, strikethrough = true },
	BlinkCmpLabelMatch = { fg = c.keyword },
	BlinkCmpLabelDescription = { link = 'PmenuExtra' },
	BlinkCmpLabelDetail = { link = 'PmenuExtra' },
	BlinkCmpKind = { fg = c.tag },
	BlinkCmpDoc = { link = 'NormalFloat' },
	BlinkCmpDocBorder = { link = 'FloatBorder' },
	BlinkCmpSignatureHelpBorder = { link = 'FloatBorder' },
	BlinkCmpKindText = { fg = c.string },
	BlinkCmpKindMethod = { fg = c.keyword },
	BlinkCmpKindFunction = { fg = c.func },
	BlinkCmpKindConstructor = { fg = c.keyword },
	BlinkCmpKindField = { fg = c.tag },
	BlinkCmpKindVariable = { fg = c.markup },
	BlinkCmpKindClass = { fg = c.entity },
	BlinkCmpKindInterface = { fg = c.entity },
	BlinkCmpKindModule = { fg = c.func },
	BlinkCmpKindProperty = { fg = c.tag },
	BlinkCmpKindUnit = { fg = c.constant },
	BlinkCmpKindValue = { fg = c.constant },
	BlinkCmpKindEnum = { fg = c.entity },
	BlinkCmpKindKeyword = { fg = c.keyword },
	BlinkCmpKindSnippet = { fg = c.markup },
	BlinkCmpKindColor = { fg = c.special },
	BlinkCmpKindFile = { fg = c.special },
	BlinkCmpKindReference = { fg = c.markup },
	BlinkCmpKindFolder = { fg = c.special },
	BlinkCmpKindEnumMember = { fg = c.regexp },
	BlinkCmpKindConstant = { fg = c.constant },
	BlinkCmpKindStruct = { fg = c.entity },
	BlinkCmpKindEvent = { fg = c.tag },
	BlinkCmpKindOperator = { fg = c.operator },
	BlinkCmpKindTypeParameter = { fg = c.lsp_parameter },

	-- Word under cursor.
	CursorWord = { bg = c.selection_inactive },
	CursorWord0 = { bg = c.selection_inactive },
	CursorWord1 = { bg = c.selection_inactive },

	-- LSP
	LspInlayHint = { fg = c.lsp_inlay_hint },
	LspSignatureActiveParameter = { italic = true },

	-- Dap.
	NvimDapVirtualText = { fg = c.regexp },

	-- DAP UI.
	DapUIScope = { fg = c.func },
	DapUIType = { fg = c.entity },
	DapUIDecoration = { fg = c.tag },
	DapUIThread = { fg = c.string },
	DapUIStoppedThread = { fg = c.special },
	DapUISource = { fg = c.regexp },
	DapUILineNumber = { fg = c.constant },
	DapUIFloatBorder = { fg = c.panel_border },
	DapUIWatchesEmpty = { fg = c.warning },
	DapUIWatchesValue = { fg = c.string },
	DapUIWatchesError = { fg = c.error },
	DapUIBreakpointsPath = { fg = c.regexp },
	DapUIBreakpointsInfo = { fg = c.constant },
	DapUIBreakpointsCurrentLine = { fg = c.constant, bold = true },

	-- Mini.
	MiniFilesTitleFocused = { fg = c.fg, bold = true },
	MiniHipatternsFixme = { fg = c.bg, bg = c.error, bold = true },
	MiniHipatternsHack = { fg = c.bg, bg = c.keyword, bold = true },
	MiniHipatternsTodo = { fg = c.bg, bg = c.tag, bold = true },
	MiniHipatternsNote = { fg = c.bg, bg = c.regexp, bold = true },
	MiniIconsAzure = { fg = c.tag },
	MiniIconsBlue = { fg = c.entity },
	MiniIconsCyan = { fg = c.regexp },
	MiniIconsGreen = { fg = c.string },
	MiniIconsGrey = { fg = c.fg },
	MiniIconsOrange = { fg = c.keyword },
	MiniIconsPurple = { fg = c.lsp_parameter },
	MiniIconsRed = { fg = c.error },
	MiniIconsYellow = { fg = c.special },
	MiniIndentscopeSymbol = { fg = c.comment },
	MiniIndentscopeSymbolOff = { fg = c.keyword },
	MiniJump = { sp = c.keyword, undercurl = true },
	MiniJump2dDim = { fg = c.comment, nocombine = true },
	MiniJump2dSpot = { fg = c.keyword, bold = true, underline = true, nocombine = true },
	MiniJump2dSpotAhead = { fg = c.entity, underline = true, nocombine = true },
	MiniJump2dSpotUnique = { fg = c.tag, bold = true, underline = true, nocombine = true },
	MiniMapNormal = { fg = c.lsp_inlay_hint, bg = c.panel_bg },
	MiniStarterItemPrefix = { fg = c.accent },
	MiniStarterFooter = { link = 'Comment' },
	MiniStatuslineDevinfo = { fg = c.fg, bg = c.panel_border },
	MiniStatuslineFileinfo = { fg = c.fg, bg = c.panel_border },
	MiniStatuslineFilename = { fg = c.fg_idle, bg = c.panel_border },
	MiniStatuslineInactive = { fg = c.fg_idle, bg = c.panel_border },
	MiniStatuslineModeCommand = { fg = c.bg, bg = c.keyword, bold = true },
	MiniStatuslineModeInsert = { fg = c.bg, bg = c.keyword, bold = true },
	MiniStatuslineModeNormal = { fg = c.bg, bg = c.keyword, bold = true },
	MiniStatuslineModeOther = { fg = c.bg, bg = c.keyword, bold = true },
	MiniStatuslineModeReplace = { fg = c.bg, bg = c.keyword, bold = true },
	MiniStatuslineModeVisual = { fg = c.bg, bg = c.keyword, bold = true },
	MiniTablineCurrent = { fg = c.fg, bg = c.bg, bold = true },
	MiniTablineFill = { fg = c.fg, bg = c.panel_border },
	MiniTablineHidden = { fg = c.comment, bg = c.panel_shadow },
	MiniTablineModifiedCurrent = { fg = c.bg, bg = c.fg, bold = true },
	MiniTablineModifiedHidden = { fg = c.panel_shadow, bg = c.comment },
	MiniTablineModifiedVisible = { fg = c.bg, bg = c.fg },
	MiniTablineVisible = { fg = c.fg, bg = c.bg },
	MiniTestFail = { fg = c.error, bold = true },
	MiniTestPass = { fg = c.string, bold = true },
	MiniTrailspace = { bg = c.vcs_removed },

	-- Render Markdown.
	RenderMarkdownH1 = { fg = c.vcs_added },
	RenderMarkdownH2 = { fg = c.string },
	RenderMarkdownH3 = { fg = c.accent },
	RenderMarkdownH4 = { fg = c.keyword },
	RenderMarkdownH5 = { fg = c.markup },
	RenderMarkdownH6 = { fg = c.constant },
	RenderMarkdownH1Bg = { bg = c.line, fg = c.vcs_added },
	RenderMarkdownH2Bg = { bg = c.line, fg = c.string },
	RenderMarkdownH3Bg = { bg = c.line, fg = c.accent },
	RenderMarkdownH4Bg = { bg = c.line, fg = c.keyword },
	RenderMarkdownH5Bg = { bg = c.line, fg = c.markup },
	RenderMarkdownH6Bg = { bg = c.line, fg = c.constant },
	RenderMarkdownQuote = { fg = c.accent },
	RenderMarkdownQuote1 = { fg = c.accent },
	RenderMarkdownQuote2 = { fg = c.keyword },
	RenderMarkdownQuote3 = { fg = c.markup },
	RenderMarkdownQuote4 = { fg = c.constant },
	RenderMarkdownQuote5 = { fg = c.constant },
	RenderMarkdownQuote6 = { fg = c.constant },
	RenderMarkdownBullet = { fg = c.vcs_added },
	RenderMarkdownDash = { fg = c.accent },
	RenderMarkdownSign = { fg = c.accent },
	RenderMarkdownMath = { fg = c.accent },
	RenderMarkdownIndent = { fg = c.accent },
	RenderMarkdownHtmlComment = { fg = c.comment },
	RenderMarkdownLink = { fg = c.tag },
	RenderMarkdownWikiLink = { fg = c.tag },
	RenderMarkdownUnchecked = { fg = c.markup },
	RenderMarkdownChecked = { fg = c.vcs_added },
	RenderMarkdownTodo = { fg = c.vcs_added },
	RenderMarkdownTableHead = { fg = c.comment },
	RenderMarkdownTableRow = { fg = c.comment },
	RenderMarkdownTableFill = { fg = c.comment },

	-- HTML
	htmlTag = { fg = c.entity },
	htmlEndTag = { link = 'htmlTag' },
	htmlTagName = { fg = c.entity },
	htmlArg = { fg = c.func },
	htmlTitle = { bold = true, fg = c.fg },
	htmlH1 = { link = 'htmlTitle' },
	htmlH2 = { link = 'htmlTitle' },
	htmlH3 = { link = 'htmlTitle' },
	htmlH4 = { link = 'htmlTitle' },
	htmlH5 = { link = 'htmlTitle' },
	htmlH6 = { link = 'htmlTitle' },
}

for group, parameters in pairs(groups) do
	vim.api.nvim_set_hl(0, group, parameters)
end
